### ISSUE TITLE
Make the link with the MDGs

### ISSUE THREAD

**Issue by brunosan** [SDG-data/web#2]
Some SDGs are related to MDGs, it can be useful to make that link to see which ones are not new Goals.

Can you help me, @zemogle

**Comment by zemogle** [comment]
Ok. Since you asked so nicely ;)

**Comment by zemogle** [comment]
Sure since you asked nicely :-)

**Comment by pythagoraswitch** [comment]
This is related to SDG-data/SDGs/issues/23

**Comment by pythagoraswitch** [comment]
FYI "MDG Indicator" and "modified MDG Indicator" are added to category in [SDG-data/SDGs/indicators.json](https://github.com/SDG-data/SDGs/blob/master/indicators.json), i.e. [L16](https://github.com/SDG-data/SDGs/blob/master/indicators.json#L16)
